<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div id="product-item-<?= $_product->getId() ?>" class="field qty"
             data-bind="scope:'productPageQtyUpdater'">
            <!-- ko template: getTemplate() --><!-- /ko -->
            <script type="text/x-magento-init">
            {
                "#product-item-<?= $_product->getId() ?>": {
                    "Magento_Ui/js/core/app": {
                       "components": {
                            "productPageQtyUpdater": {
                                "component": "qtyUpdater",
                                "defaultQty": <?= $block->getProductDefaultQty() * 1 ?>
                            }
                        }
                    }
                }
            }
            </script>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
